mongo-staging:
  image: mongo:3.0.4
  command: --auth
  volumes:
    - /var/data/mongodb:/data/db
  ports:
    - "27017:27017"
  tags:
    - staging
  autorestart: always
muzhack-staging:
  image: quay.io/aknuds1/muzhack:latest
  links:
    - mongo-staging:db
  environment:
    - ROOT_URL=https://staging.muzhack.com
    - MONGO_URL
    - METEOR_SETTINGS
  tags:
    - staging
  autorestart: always
nginx-staging:
  image: aknudsen/meteor-frontend-server
  command: /start.sh
  tags:
    - staging
  autorestart: always
  ports:
    - "443:443"
    - "80:80"
  volumes:
    - /etc/nginx/ssl/bundle.crt:/bundle.crt
    - /etc/nginx/ssl/private.key:/private.key
  links:
    - muzhack-staging:backend
logspout-staging:
  image: gliderlabs/logspout
  command: syslog://logs3.papertrailapp.com:19740
  tags:
    - staging
  autorestart: always
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  deployment_strategy: every_node
